version: '3.9'

services:

  crowd-control-dev:
    user: 185:33
    image: 'docker.benevolo.de/stiehl-seine-perlen/crowd-control:dev'
    restart: unless-stopped
    ports:
      - 8089:8082
    environment:
      QUARKUS_DATASOURCE_DB_KIND: POSTGRESQL
      QUARKUS_DATASOURCE_USERNAME: crowd-control
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_HTTP_PORT: 8082
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-dev:5432/member
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
      QUARKUS_HTTP_CORS_ORIGINS: "https://dev.benevolo.de" ## allow frontend as origin
      MJ_APIKEY_PUBLIC: ${MJ_APIKEY_PUBLIC}
      MJ_APIKEY_PRIVATE: ${MJ_APIKEY_PRIVATE}

    networks:
      - crowd-control
      - kafka
      - nginx-proxy-manager

  postgres-dev:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: member
      POSTGRES_USER: crowd-control
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /microservices/crowd-control/postgres/data/:/var/lib/postgresql/data/
    networks:
      - crowd-control

networks:
  kafka:
    external: true
  crowd-control:
    external: true
  nginx-proxy-manager:
    external: true
